// import "./api/CustomCommand/CustomCommand";
// import "./api/ConsoleCommandUI/IndexConsoleC";
import "./api/GametestOptions/EventHandler";
import "./api/Watchdog";
// import "./api/InfoTick/MainTick";
import "./api/ChangePermutation";
// import "./extension/Entity";
// import "./api/EntityComponent";
import "./api/GametestOptions/Options";
import "./commands/index";
import "./test";
import "./forms/Event";
