site_name: FrankyRayMS's Personal Addon BP Docs
site_url: https://example.com/

nav:
  - Scripts:
    - Command Component: "scripts/commandcomp.md"

theme:
  name: material
  features:
    - navigation.tabs
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences